from common.constants import PRODUCT_ITEM_DAILY_TABLE, LAST_STATE_PRODUCT_ITEM_TABLE, PRODUCT_ITEM_DAILY_REVENUE_TABLE, \
    PRODUCT_ITEM_DAILY_STAGING_TABLE, LAST_STATE_PRODUCT_ITEM_STAGING_TABLE, PRODUCT_ITEM_DAILY_REVENUE_STAGING_TABLE

pid_ddl = f"CREATE TABLE {PRODUCT_ITEM_DAILY_STAGING_TABLE} (id STRING NOT NULL,sold INT NOT NULL,price FLOAT NOT NULL,sellPrice FLOAT,crawledDateMs TIMESTAMP NOT NULL) USING iceberg PARTITIONED BY (days(crawledDateMs));"
state_pi_ddl = f"CREATE TABLE {LAST_STATE_PRODUCT_ITEM_STAGING_TABLE} (id STRING NOT NULL,sold INT NOT NULL,crawledDateMs TIMESTAMP NOT NULL) USING iceberg;"
pid_revenue_ddl = f"CREATE TABLE {PRODUCT_ITEM_DAILY_REVENUE_STAGING_TABLE} (id STRING NOT NULL,dailySold INT NOT NULL,price FLOAT NOT NULL,sellPrice FLOAT, gmv FLOAT NOT NULL, crawledDateMs TIMESTAMP NOT NULL,createdDate TIMESTAMP) USING iceberg PARTITIONED BY (days(crawledDateMs));"
