LAST_STATE_PRODUCT_ITEM_TABLE = 'ecm_catalog.report.last_state_product_item'
PRODUCT_ITEM_DAILY_TABLE = 'ecm_catalog.report.product_item_daily'
PRODUCT_ITEM_DAILY_REVENUE_TABLE = 'ecm_catalog.report.product_item_daily_revenue'
PARSED_BUCKET = 'parsed-data'
JOB_STATUS = {
    "IDLE": 'IDLE',
    "RUNNING": 'RUNNING',
    "COMPLETED": 'COMPLETED',
    "ERROR": 'ERROR'
}
CALC_DAILY_REVENUE_PROCESS = {
    "INIT_TRACKING_JOB": 'INIT_TRACKING_JOB',
    "TRANSFER_DATA_DAILY_SNAPSHOT_TO_ICEBERG": "TRANSFER_DATA_DAILY_SNAPSHOT_TO_ICEBERG",
    "CALC_DALY_REVENUE": "CALC_DALY_REVENUE",
    "TRANSFER_DAILY_REVENUE_DATA_TO_KAFKA": "TRANSFER_DAILY_REVENUE_DATA_TO_KAFKA",
    "CLEAR_OLDER_THAN_N_MONTHS": "CLEAR_OLDER_THAN_N_MONTHS",
}
POSTGRESQL_CONN = 'postgresql_default'
REPORT_TABLE = {
    "JOBS": "jobs"
}